version: '3'
services:
  app:
    container_name: backend
    build:
      context: ./backend-api
    ports:
      - 5300:5300
    restart: on-failure
    environment:
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - PORT=5300
    depends_on:
      - fullstack-postgres

  fullstack-postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hello_db
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./backend-db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database_postgres:
