swagger: "2.0"
info:
  title: thingulator Service
  description: Service for adding numbers, a Goa teaser
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /things/:
    get:
      tags:
      - thing
      summary: list thing
      operationId: thing#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ThingStoredThingResponseTinyCollection'
      schemes:
      - http
definitions:
  StoredThingResponseTiny:
    title: 'Mediatype identifier: vnd.goa.thing; view=default'
    type: object
    properties:
      id:
        type: integer
        example: 2387476665444181728
        format: int64
      name:
        type: string
        description: Name of Thing
        example: Apple
        maxLength: 100
    description: StoredThingResponse result type (tiny view) (default view)
    example:
      id: 3001078444823167151
      name: Apple
    required:
    - id
    - name
  ThingStoredThingResponseTinyCollection:
    title: 'Mediatype identifier: vnd.goa.thing; type=collection; view=tiny'
    type: array
    items:
      $ref: '#/definitions/StoredThingResponseTiny'
    description: ThingStoredThingResponseTinyCollection is the result type for an
      array of StoredThingResponseTiny (default view)
    example:
    - id: 15189299754580197672
      name: Apple
    - id: 15189299754580197672
      name: Apple
    - id: 15189299754580197672
      name: Apple
    - id: 15189299754580197672
      name: Apple
